---
kids_sonarr_enabled: false
kids_sonarr_available_externally: false

# directories
kids_sonarr_data_directory: "{{ docker_home }}/kids_sonarr"
kids_sonarr_tv_directory: "{{ kids_tv_root }}"
kids_sonarr_download_directory: "{{ downloads_root }}"

# uid / gid
kids_sonarr_user_id: "0"
kids_sonarr_group_id: "0"

# network
kids_sonarr_port: "8990"
kids_sonarr_hostname: "kids_sonarr"

# specs
kids_sonarr_memory: 1g
